name = "shulisoccer-comment-events"
main = "workers/comment-events.ts"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "shulisoccer"
database_id = "318b6326-ccf8-46e8-9809-9a320978ea31"
migrations_dir = "migrations"

[[queues.consumers]]
queue = "shulisoccer-comment-events"
max_batch_size = 10
max_batch_timeout = 5
max_retries = 3
