-- ============================================================
-- 0002_update_from_excel.sql
-- Source: 球员信息统计.xlsx (2026-05-26)
-- Generated by scripts/generate_migration.py — DO NOT hand-edit.
-- See scripts/migration_report.txt for the full diff.
-- ============================================================

-- ---------- UPDATE existing players ----------
UPDATE players SET number = 19, position = '中后卫', positionGroup = 'defender', province = '浙江湖州', age = 21, birthday = '2004-10-22', height = 184, weight = 72, starts = 12, subs = 0, goals = 3 WHERE filename = 'shl';
UPDATE players SET number = 20, position = '左边锋', positionGroup = 'forward', province = '四川成都', age = 20, birthday = '2006-05-24', height = 181, weight = 62, starts = 5, subs = 3, goals = 0 WHERE filename = 'hyc';
UPDATE players SET number = 12, position = '中锋', positionGroup = 'forward', province = '广西桂林', age = 22, birthday = '2003-11-10', height = 180, weight = 67, starts = 11, subs = 2, goals = 0 WHERE filename = 'pyc';
UPDATE players SET number = 18, position = '左边锋', positionGroup = 'forward', province = '湖南邵阳', age = 20, birthday = '2006-02-18', height = 169, weight = 65, starts = 0, subs = 2, goals = 0 WHERE filename = 'cyq';
UPDATE players SET number = 25, position = '门将', positionGroup = 'goalkeeper', province = '浙江杭州', age = 20, birthday = '2006-03-25', height = 177, weight = 68, starts = 5, subs = 0, goals = 0 WHERE filename = 'dmx';
UPDATE players SET number = 30, position = '前腰', positionGroup = 'midfield', province = '福建泉州', age = 20, birthday = '2005-11-15', height = 173, weight = 65, starts = 2, subs = 1, goals = 0 WHERE filename = 'ljy';
UPDATE players SET number = 22, position = '左后卫', positionGroup = 'defender', province = '河南安阳', age = 22, birthday = '2004-03-07', height = 175, weight = 62, starts = 15, subs = 1, goals = 1 WHERE filename = 'zjz1';
UPDATE players SET number = 21, position = '后腰', positionGroup = 'midfield', province = '陕西西安', age = 22, birthday = '2004-08-15', height = 170, weight = 78, starts = 2, subs = 8, goals = 0 WHERE filename = 'lds';
UPDATE players SET number = 15, position = '右后卫', positionGroup = 'defender', province = '浙江湖州', age = 22, birthday = '2004-02-13', height = 170, weight = 63, starts = 9, subs = 5, goals = 4 WHERE filename = 'syh';
UPDATE players SET number = 14, position = '中锋', positionGroup = 'forward', province = '广东深圳', age = 21, birthday = '2005-07-21', height = 174, weight = 94, starts = 2, subs = 4, goals = 2, name = '周玹安', filename = 'zxa' WHERE filename = 'zjz2';
UPDATE players SET number = 13, position = '右后卫', positionGroup = 'defender', province = '广东广州', age = 21, birthday = '2005-03-22', height = 171, weight = 58, starts = 0, subs = 2, goals = 0 WHERE filename = 'zd';
UPDATE players SET number = 16, position = '中锋', positionGroup = 'forward', province = '四川成都', age = 20, birthday = '2006-07-08', height = 180, weight = 68, starts = 0, subs = 2, goals = 0 WHERE filename = 'dlr';
UPDATE players SET number = 9, position = '中锋', positionGroup = 'forward', province = '广东东莞', age = 21, birthday = '2005-06-05', height = 171, weight = 72, starts = 4, subs = 0, goals = 1 WHERE filename = 'qym';
UPDATE players SET number = 61, position = '中锋', positionGroup = 'forward', province = '北京海淀', age = 21, birthday = '2005-06-16', height = 180, weight = 66, starts = 3, subs = 2, goals = 0 WHERE filename = 'zh';
UPDATE players SET number = 10, position = '后腰', positionGroup = 'midfield', province = '北京朝阳', age = 21, birthday = '2005-04-28', height = 183, weight = 67, starts = 9, subs = 3, goals = 1 WHERE filename = 'zxm';
UPDATE players SET number = 7, position = '右边锋', positionGroup = 'forward', province = '湖南郴州', age = 20, birthday = '2005-12-28', height = 177, weight = 66, starts = 12, subs = 0, goals = 2 WHERE filename = 'zhy';
UPDATE players SET number = 4, position = '后腰', positionGroup = 'midfield', province = '广东广州', age = 20, birthday = '2006-01-08', height = 181, weight = 78, starts = 1, subs = 1, goals = 0 WHERE filename = 'hjh';
UPDATE players SET number = 23, position = '中锋', positionGroup = 'forward', province = '福建厦门', age = 22, birthday = '2004-04-10', height = 173, weight = 67, starts = 1, subs = 10, goals = 1 WHERE filename = 'ljh';
UPDATE players SET number = 8, position = '中场', positionGroup = 'midfield', province = '湖北武汉', age = 22, birthday = '2003-06-18', height = 175, weight = 68, starts = 14, subs = 2, goals = 0 WHERE filename = 'ccx';

-- ---------- INSERT new players ----------
INSERT INTO players (positionGroup, position, number, filename, name, enName, club, nationality, nationalityFlag, province, age, birthday, height, weight, foot, starts, subs, goals) VALUES
  ('defender', '右后卫', 38, 'hzy', '贺梓尧', 'He Ziyao', '树礼书院', '中国', '🇨🇳', '湖南株洲', 18, '2007-09-28', 179, 66, NULL, 3, 0, 0),
  ('defender', '左后卫', 26, 'wky', '王鲲云', 'Wang Kunyun', '树礼书院', '中国', '🇨🇳', '山东威海', 19, '2006-09-26', 182, 67, NULL, 0, 0, 0),
  ('goalkeeper', '守门员', 99, 'hht', '胡皓天', 'Hu Haotian', '树礼书院', '中国', '🇨🇳', '浙江台州', 19, '2007-01-25', 178, 72, NULL, 0, 1, 0),
  ('defender', '右后卫', 17, 'wyk', '王艺恺', 'Wang Yikai', '树礼书院', '中国', '🇨🇳', '陕西西安', 19, '2006-09-23', 175, 65, NULL, 0, 1, 0),
  ('forward', '左边锋', 24, 'czp', '陈子佩', 'Chen Zipei', '树礼书院', '中国', '🇨🇳', '江苏苏州', 19, '2007-03-01', 169, 67, NULL, 2, 0, 0),
  ('midfield', '前腰', 6, 'mly', '马麓原', 'Ma Luyuan', '树礼书院', '中国', '🇨🇳', '北京海淀', 18, '2007-06-09', 185, 70, NULL, 4, 0, 2),
  ('defender', '右后卫', 2, 'yy', '袁野', 'Yuan Ye', '树礼书院', '中国', '🇨🇳', '广东深圳', 18, '2007-07-08', 180, 70, NULL, 0, 0, 0),
  ('defender', '中后卫', 11, 'zxt', '张熙泰', 'Zhang Xitai', '树礼书院', '中国', '🇨🇳', '北京海淀', 17, '2008-12-22', 182, 70, NULL, 3, 1, 0),
  ('forward', '右边锋', 37, 'mym', '马一鸣', 'Ma Yiming', '树礼书院', '中国', '🇨🇳', '辽宁沈阳', 18, '2007-06-19', 181, 55, NULL, 0, 0, 0),
  ('forward', '中锋', 3, 'lx', '廖翔', 'Liao Xiang', '树礼书院', '中国', '🇨🇳', '广东中山', 18, '2007-06-01', 180, 70, NULL, 0, 0, 0);

-- ---------- Manual fixes: keep topScorers in sync with renames ----------
UPDATE topScorers SET name = '周玹安' WHERE name = '周俊哲';
