export const goalkeeper = [
  {
    position: "守门员",
    number: 99,
    filename: "pyc",
    name: "庞宇程",
    enName: "Pang Yucheng",
    club: "树礼书院",
    nationality: "中国",
    nationalityFlag: "🇨🇳",
    age: 20,
    birthday: "2004-05-12",
    height: 185,
    weight: 75,
    foot: "右脚",
    starts: 3,
    subs: 0,
    goals: 0,
  },
  {
    position: "守门员",
    number: 24,
    filename: "dmx",
    name: "戴铭希",
    enName: "Dai Mingxi",
    club: "树礼书院",
    nationality: "中国",
    nationalityFlag: "🇨🇳",
    age: 19,
    birthday: "2005-03-21",
    height: 182,
    weight: 72,
    foot: "右脚",
    starts: 1,
    subs: 0,
    goals: 0,
  },
];

export const defender = [
  {
    position: "中后卫",
    number: 19,
    filename: "shl",
    name: "沈泓立(C)",
    enName: "Shen Hongli",
    club: "树礼书院",
    nationality: "中国",
    nationalityFlag: "🇨🇳",
    age: 21,
    birthday: "2003-08-09",
    height: 183,
    weight: 76,
    foot: "右脚",
    starts: 4,
    subs: 0,
    goals: 1,
  },
  {
    position: "中后卫",
    number: 17,
    filename: "yxm",
    name: "叶曦珉",
    enName: "Ye Ximin",
    club: "树礼书院",
    nationality: "中国",
    nationalityFlag: "🇨🇳",
    age: 20,
    birthday: "2004-02-15",
    height: 180,
    weight: 73,
    foot: "右脚",
    starts: 2,
    subs: 0,
    goals: 1,
  },
  {
    position: "右后卫",
    number: 66,
    filename: "zxm",
    name: "郑袭明",
    enName: "Zheng Ximing",
    club: "树礼书院",
    nationality: "中国",
    nationalityFlag: "🇨🇳",
    age: 20,
    birthday: "2004-07-18",
    height: 178,
    weight: 70,
    foot: "右脚",
    starts: 4,
    subs: 0,
    goals: 1,
  },
  {
    position: "右后卫",
    number: 64,
    filename: "zd",
    name: "朱丹",
    enName: "Zhu Dan",
    club: "树礼书院",
    nationality: "中国",
    nationalityFlag: "🇨🇳",
    age: 19,
    birthday: "2005-01-10",
    height: 175,
    weight: 68,
    foot: "右脚",
    starts: 0,
    subs: 2,
    goals: 0,
  },
  {
    position: "左后卫",
    number: 25,
    filename: "zjz1",
    name: "张锦泽",
    enName: "Zhang Jinze",
    club: "树礼书院",
    nationality: "中国",
    nationalityFlag: "🇨🇳",
    age: 20,
    birthday: "2004-11-23",
    height: 180,
    weight: 72,
    foot: "左脚",
    starts: 4,
    subs: 0,
    goals: 1,
  },
];

export const midfield = [
  {
    position: "中场",
    number: 8,
    filename: "modric",
    name: "莫德里奇",
    enName: "Luka Modrić",
    club: "皇家马德里",
    nationality: "克罗地亚",
    nationalityFlag: "🇭🇷",
    age: 38,
    birthday: "1985-09-09",
    height: 172,
    weight: 66,
    foot: "右脚",
    starts: 40,
    subs: 10,
    goals: 5,
  },
  {
    position: "中场",
    number: 6,
    filename: "kdb",
    name: "德布劳内",
    enName: "Kevin De Bruyne",
    club: "曼城",
    nationality: "比利时",
    nationalityFlag: "🇧🇪",
    age: 33,
    birthday: "1991-06-28",
    height: 181,
    weight: 70,
    foot: "右脚",
    starts: 38,
    subs: 8,
    goals: 10,
  },
  {
    position: "中场",
    number: 18,
    filename: "kroos",
    name: "克罗斯",
    enName: "Toni Kroos",
    club: "皇家马德里",
    nationality: "德国",
    nationalityFlag: "🇩🇪",
    age: 34,
    birthday: "1990-01-04",
    height: 183,
    weight: 76,
    foot: "右脚",
    starts: 36,
    subs: 6,
    goals: 6,
  },
];

export const forward = [
  {
    position: "前锋",
    number: 9,
    filename: "kane",
    name: "哈里-凯恩",
    enName: "Harry Kane",
    club: "拜仁慕尼黑",
    nationality: "英格兰",
    nationalityFlag: "🇬🇧",
    age: 31,
    birthday: "1993-07-28",
    height: 188,
    weight: 86,
    foot: "右脚",
    starts: 40,
    subs: 8,
    goals: 39,
  },
  {
    position: "前锋",
    number: 17,
    filename: "mbappe",
    name: "奥利塞",
    enName: "Michael Olise",
    club: "切尔西",
    nationality: "法国",
    nationalityFlag: "🇫🇷",
    age: 22,
    birthday: "2001-12-12",
    height: 184,
    weight: 76,
    foot: "左脚",
    starts: 45,
    subs: 7,
    goals: 20,
  },
  {
    position: "前锋",
    number: 10,
    filename: "sane",
    name: "萨内",
    enName: "Leroy Sané",
    club: "拜仁慕尼黑",
    nationality: "德国",
    nationalityFlag: "🇩🇪",
    age: 28,
    birthday: "1996-01-11",
    height: 183,
    weight: 80,
    foot: "左脚",
    starts: 38,
    subs: 8,
    goals: 13,
  },
  {
    position: "前锋",
    number: 11,
    filename: "kolo",
    name: "金斯利-科曼",
    enName: "Kingsley Coman",
    club: "拜仁慕尼黑",
    nationality: "法国",
    nationalityFlag: "🇫🇷",
    age: 28,
    birthday: "1996-06-13",
    height: 180,
    weight: 76,
    foot: "右脚",
    starts: 35,
    subs: 8,
    goals: 9,
  },
  {
    position: "前锋",
    number: 25,
    filename: "thomas",
    name: "托马斯-穆勒",
    enName: "Thomas Müller",
    club: "拜仁慕尼黑",
    nationality: "德国",
    nationalityFlag: "🇩🇪",
    age: 34,
    birthday: "1989-09-13",
    height: 185,
    weight: 75,
    foot: "右脚",
    starts: 40,
    subs: 6,
    goals: 8,
  },
  {
    position: "前锋",
    number: 7,
    filename: "gnabry",
    name: "格纳布里",
    enName: "Serge Gnabry",
    club: "拜仁慕尼黑",
    nationality: "德国",
    nationalityFlag: "🇩🇪",
    age: 29,
    birthday: "1995-07-14",
    height: 176,
    weight: 77,
    foot: "右脚",
    starts: 36,
    subs: 8,
    goals: 7,
  },
];

export const Retired = [
  { filename: "wjm", name: "吴嘉木", position: "Forward", number: 34, grade: 2020 },
];
